#ifndef SRC_SCENES_MANAGE_SCENES_SCENE_MAP_COMPONENTS_BOOTSTRAP_H
#define SRC_SCENES_MANAGE_SCENES_SCENE_MAP_COMPONENTS_BOOTSTRAP_H

#include "SpawnMapComponent.h"
#include "TerrainComponent.h"
#include "WallsMapComponent.h"

#endif // SRC_SCENES_MANAGE_SCENES_SCENE_MAP_COMPONENTS_BOOTSTRAP_H