#ifndef SRC_SCENES_PLAYER_ZOMBIE_SCENE_ZOMBIE_SYSTEMS_BOOTSTRAP_H
#define SRC_SCENES_PLAYER_ZOMBIE_SCENE_ZOMBIE_SYSTEMS_BOOTSTRAP_H

#include "ZombieDrawSystem.h"
#include "ZombieMoveSystem.h"
#include "ZombieTargetingSystem.h"

#endif // SRC_SCENES_PLAYER_ZOMBIE_SCENE_ZOMBIE_SYSTEMS_BOOTSTRAP_H