#ifndef SRC_ENTITIES_SCENE_COMPONENTS_BOOTSTRAP_H
#define SRC_ENTITIES_SCENE_COMPONENTS_BOOTSTRAP_H

#include "GameTitleComponent.h"
#include "SceneComponent.h"

#endif // SRC_ENTITIES_SCENE_COMPONENTS_BOOTSTRAP_H