#ifndef SRC_SCENES_MANAGE_SCENES_SCENE_MAP_BOOTSTRAP_H
#define SRC_SCENES_MANAGE_SCENES_SCENE_MAP_BOOTSTRAP_H

#include "./components/Bootstrap.h"
#include "./systems/Bootstrap.h"

#endif // SRC_SCENES_MANAGE_SCENES_SCENE_MAP_BOOTSTRAP_H