#ifndef SRC_SCENES_PLAYER_ZOMBIE_SCENE_PLAYER_BOOTSTRAP_H
#define SRC_SCENES_PLAYER_ZOMBIE_SCENE_PLAYER_BOOTSTRAP_H

#include "./components/Bootstrap.h"
#include "./systems/Bootstrap.h"

#endif // SRC_SCENES_PLAYER_ZOMBIE_SCENE_PLAYER_BOOTSTRAP_H